[tool.poetry]
name = "py-cinema"
version = "0.1.0"
description = ""
authors = ["Dmytro <ys33ys33ys55@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.139.2"
uvicorn = "^0.51.0"
sqlalchemy = "^2.0.51"
pydantic = "^2.13.4"
alembic = "^1.18.5"
celery = "^5.6.3"
pydantic-settings = "^2.14.2"
black = "^26.5.1"
aiosqlite = "^0.22.1"
greenlet = "^3.5.3"
passlib = "^1.7.4"
bcrypt = "4.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
